from innovations_trading import *


def make_products():

    # Farming
    profession_recipe("Farming", FD("carrot_crate"), 1, S, 1)
    profession_recipe("Farming", FD("potato_crate"), 1, S, 1)
    profession_recipe("Farming", FD("beetroot_crate"), 1, S, 1)
    profession_recipe("Farming", FD("cabbage_crate"), 1, S, 1)
    profession_recipe("Farming", FD("tomato_crate"), 1, S, 1)
    profession_recipe("Farming", FD("onion_crate"), 1, S, 1)
    profession_recipe("Farming", FD("rice_bag"), 1, S, 1)
    profession_recipe("Farming", FD("canvas"), 32, S, 1)
    profession_recipe("Farming", MC("apple"), 32, S, 1)
    profession_recipe("Farming", MC("sweet_berries"), 8, S, 1)
    profession_recipe("Farming", MC("cocoa_beans"), 16, S, 1)
    profession_recipe("Farming", MC("honey_bottle"), 8, S, 1)
    profession_recipe("Farming", MC("honeycomb"), 4, S, 1)
    profession_recipe("Farming", MC("dandelion"), 16, S, 1)
    profession_recipe("Farming", MC('oxeye_daisy'), 16, S, 1)
    profession_recipe("Farming", MC('bread'), 8, S, 1)
    profession_recipe("Farming", MC('brown_mushroom'), 8, S, 1)
    profession_recipe("Farming", MC('red_mushroom'), 8, S, 1)
    profession_recipe("Farming", BOP("toadstool"), 8, S, 1)
    profession_recipe("Farming", MC("kelp"), 64, S, 1)
    profession_recipe("Farming", MC("pumpkin"), 4, S, 1)
    profession_recipe("Farming", MC("wool"), 16, S, 1, True, "wool")
    profession_recipe("Farming", MC("melon"), 2, S, 1)

    # Carpentry
    profession_recipe("Carpentry", MC("oak_log"), 64, S, 1)
    profession_recipe("Carpentry", MC("spruce_log"), 64, S, 1)
    profession_recipe("Carpentry", MC("jungle_log"), 64, S, 1)
    profession_recipe("Carpentry", MC("dark_oak_log"), 64, S, 1)
    profession_recipe("Carpentry", BOP("redwood_log"), 64, S, 1)
    profession_recipe("Carpentry", MC("fir_log"), 64, S, 1)
    profession_recipe("Carpentry", MC("umbran_log"), 64, S, 1)
    profession_recipe("Carpentry", MC("dead_log"), 64, S, 1)
    profession_recipe("Carpentry", MC("acacia_log"), 64, S, 2)
    profession_recipe("Carpentry", MC("birch_log"), 64, S, 2)
    profession_recipe("Carpentry", BOP("cherry_log"), 64, S, 2)
    profession_recipe("Carpentry", BOP("willow_log"), 64, S, 3)
    profession_recipe("Carpentry", BOP("palm_log"), 64, S, 3)
    profession_recipe("Carpentry", BOP("mahogany_log"), 64, S, 3)
    profession_recipe("Carpentry", BOP("magic_log"), 64, S, 3)
    profession_recipe("Carpentry", MC("crimson_stem"), 64, S, 4)
    profession_recipe("Carpentry", MC("warped_stem"), 64, S, 4)
    profession_recipe("Carpentry", BOP("hellbark_log"), 64, S, 8)

    # Mining
    profession_recipe("Mining", MC("raw_iron"), 16, S, 8)
    profession_recipe("Mining", MC("raw_copper"), 16, S, 8)
    profession_recipe("Mining", CR("raw_zinc"), 16, S, 8)
    profession_recipe("Mining", MC("raw_gold"), 16, S, 10)
    profession_recipe("Mining", F("raw_materials/nickel"), 16, S, 12, True, "raw_nickel")
    profession_recipe("Mining", F("raw_materials/lead"), 16, S, 12, True, "raw_lead")
    profession_recipe("Mining", MC("andesite"), 64, S, 1)
    profession_recipe("Mining", MC("granite"), 64, S, 1)
    profession_recipe("Mining", MC("diorite"), 64, S, 1)
    profession_recipe("Mining", MC("sandstone"), 64, S, 1)
    profession_recipe("Mining", CR("limestone"), 64, S, 1)
    profession_recipe("Mining", CR("gabbro"), 64, S, 1)
    profession_recipe("Mining", MC("tuff"), 64, S, 2)
    profession_recipe("Mining", MC("calcite"), 8, S, 2)
    profession_recipe("Mining", TE("cinnibar"), 16, S, 6)
    profession_recipe("Mining", TE("sulfur"), 16, S, 6)
    profession_recipe("Mining", TE("niter"), 16, S, 6)
    profession_recipe("Mining", MC("lapis_lazuli"), 16, S, 6)
    profession_recipe("Mining", TE("apatite"), 1, S, 4)
    profession_recipe("Mining", TE("sapphire"), 1, S, 10)
    profession_recipe("Mining", TE("ruby"), 1, S, 10)
    profession_recipe("Mining", MC("diamond"), 1, S, 14)
    profession_recipe("Mining", MC("coal"), 16, S, 2)

    # Masonry
    profession_recipe("Masonry", SP("checker_block"), 64, S, 4)
    profession_recipe("Masonry", AP("basalt_tiles"), 64, S, 6)
    profession_recipe("Masonry", TC("seared_bricks"), 64, S, 10)
    profession_recipe("Masonry", AP("sunmetal_block"), 64, S, 8)
    profession_recipe("Masonry", AP("osseous_bricks"), 64, S, 6)
    profession_recipe("Masonry", AP("packed_ice_pillar"), 64, S, 8)
    profession_recipe("Masonry", AP("flint_tiles"), 64, S, 4)
    profession_recipe("Masonry", AP("abyssaline"), 64, S, 12)
    profession_recipe("Masonry", AP("gilded_sandstone"), 64, S, 10)
    profession_recipe("Masonry", MC("bricks"), 64, S, 6)
    profession_recipe("Masonry", TC("mud_bricks"), 64, S, 6)
    profession_recipe("Masonry", AP("olivestone_bricks"), 64, S, 4)
    profession_recipe("Masonry", MC("quartz_bricks"), 64, S, 18)
    profession_recipe("Masonry", AP("algal_bricks"), 64, S, 6)
    profession_recipe("Masonry", TC("lavawood"), 64, S, 6)
    profession_recipe("Masonry", CR("ornate_iron_window"), 64, S, 10)
    profession_recipe("Masonry", MC("mossy_cobblestone"), 64, S, 6)
    profession_recipe("Masonry", F("glazed_terracotta"), 64, S, 6, True, "glazed_terracotta")
    profession_recipe("Masonry", SP("daub_brace"), 64, S, 8)

    # Hunting
    profession_recipe("Hunting", RQ("slime_pearl"), 1, S, 6)
    profession_recipe("Hunting", RQ("catalyzing_gland"), 1, S, 10)
    profession_recipe("Hunting", RQ("witch_hat"), 1, S, 15)
    profession_recipe("Hunting", RQ("squid_beak"), 1, S, 3)
    profession_recipe("Hunting", RQ("withered_rib"), 1, S, 15)
    profession_recipe("Hunting", RQ("rib_bone"), 1, S, 5)
    profession_recipe("Hunting", RQ("zombie_heart"), 1, S, 5)
    profession_recipe("Hunting", RQ("chelicerae"), 1, S, 5)
    profession_recipe("Hunting", RQ("bat_wing"), 1, S, 10)
    profession_recipe("Hunting", RQ("frozen_core"), 1, S, 4)
    profession_recipe("Hunting", RQ("nebulous_heart"), 1, S, 7)
    profession_recipe("Hunting", RQ("molten_core"), 1, S, 6)
    profession_recipe("Hunting", RQ("eye_of_the_storm"), 1, S, 12)
    profession_recipe("Hunting", MC("phantom_membrane"), 1, S, 8)
    profession_recipe("Hunting", MC("rabbit_foot"), 1, S, 8)
    profession_recipe("Hunting", MC("nether_star"), 1, G, 1)
    profession_recipe("Hunting", MC("dragon_breath"), 1, S, 1)
    profession_recipe("Hunting", MC("ghast_tear"), 1, S, 18)
    profession_recipe("Hunting", MC("dragon_egg"), 1, G, 2)
    profession_recipe("Hunting", RQ("guardian_spike"), 1, S, 6)

    # Cooking
    profession_recipe("Cooking", CR("bar_of_chocolate"), 16, S, 4)
    profession_recipe("Cooking", CR("honeyed_apple"), 16, S, 4)
    profession_recipe("Cooking", CR("builders_tea"), 16, S, 4)
    profession_recipe("Cooking", FD("hot_cocoa"), 16, S, 5)
    profession_recipe("Cooking", FD("tomato_sauce"), 8, S, 3)
    profession_recipe("Cooking", FD("apple_pie_slice"), 16, S, 3)
    profession_recipe("Cooking", FD("chocolate_pie_slice"), 16, S, 4)
    profession_recipe("Cooking", FD("sweet_berry_cheesecake_slice"), 17, S, 3)
    profession_recipe("Cooking", FD("cake_slice"), 14, S, 3)
    profession_recipe("Cooking", FD("sweet_berry_cookie"), 64, S, 2)
    profession_recipe("Cooking", FD("honey_cookie"), 64, S, 2)
    profession_recipe("Cooking", MC("cookie"), 64, S, 2)
    profession_recipe("Cooking", FD("melon_popsicle"), 16, S, 7)
    profession_recipe("Cooking", FD("fruit_salad"), 16, S, 7)
    profession_recipe("Cooking", FD("mixed_salad"), 16, S, 9)
    profession_recipe("Cooking", FD("nether_salad"), 16, S, 5)
    profession_recipe("Cooking", FD("barbecue_stick"), 16, S, 6)
    profession_recipe("Cooking", FD("egg_sandwich"), 16, S, 5)
    profession_recipe("Cooking", FD("chicken_sandwich"), 16, S, 9)
    profession_recipe("Cooking", FD("bacon_sandwich"), 16, S, 9)
    profession_recipe("Cooking", FD("hamburger"), 16, S, 11)
    profession_recipe("Cooking", FD("mutton_wrap"), 16, S, 10)
    profession_recipe("Cooking", FD("dumplings"), 16, S, 7)
    profession_recipe("Cooking", FD("stuffed_potato"), 16, S, 6)
    profession_recipe("Cooking", FD("cabbage_rolls"), 16, S, 5)
    profession_recipe("Cooking", FD("beef_stew"), 16, S, 8)
    profession_recipe("Cooking", FD("chicken_soup"), 16, S, 9)
    profession_recipe("Cooking", MC("rabbit_stew"), 16, S, 10)
    profession_recipe("Cooking", MC("beetroot_soup"), 16, S, 7)
    profession_recipe("Cooking", MC("pumpkin_pie"), 16, S, 3)
    profession_recipe("Cooking", FD("vegetable_soup"), 16, S, 9)
    profession_recipe("Cooking", SP("pancake"), 32, S, 4)
    profession_recipe("Cooking", FD("fish_stew"), 16, S, 9)
    profession_recipe("Cooking", FD("fried_rice"), 16, S, 8)
    profession_recipe("Cooking", FD("pumpkin_soup"), 16, S, 8)
    profession_recipe("Cooking", FD("baked_cod_stew"), 16, S, 9)
    profession_recipe("Cooking", FD("noodle_soup"), 16, S, 9)
    profession_recipe("Cooking", FD("pasta_with_meatballs"), 16, S, 10)
    profession_recipe("Cooking", FD("pasta_with_mutton_chop"), 16, S, 10)
    profession_recipe("Cooking", FD("roasted_mutton_chops"), 16, S, 9)
    profession_recipe("Cooking", FD("vegetable_noodles"), 16, S, 10)
    profession_recipe("Cooking", FD("steak_and_potatoes"), 16, S, 9)
    profession_recipe("Cooking", FD("ratatouille"), 16, S, 9)
    profession_recipe("Cooking", FD("squid_ink_pasta"), 16, S, 11)
    profession_recipe("Cooking", FD("roast_chicken"), 16, S, 7)
    profession_recipe("Cooking", FD("stuffed_pumpkin"), 16, S, 7)
    profession_recipe("Cooking", FD("honey_glazed_ham"), 16, S, 7)
    profession_recipe("Cooking", FD("shepherds_pie"), 16, S, 7)
    profession_recipe("Cooking", AC("sushi"), 16, S, 3)
    profession_recipe("Cooking", CR("sweet_roll"), 16, S, 4)

    # Fishing
    profession_recipe("Fishing", MC("cod"), 3, S, 1)
    profession_recipe("Fishing", MC("salmon"), 3, S, 1)
    profession_recipe("Fishing", MC("pufferfish"), 3, S, 1)
    profession_recipe("Fishing", MC("tropical_fish"), 3, S, 1)
    profession_recipe("Fishing", AC("atlantic_herring"), 3, S, 6)
    profession_recipe("Fishing", AC("synodontis"), 3, S, 6)
    profession_recipe("Fishing", AC("bluegill"), 3, S, 6)
    profession_recipe("Fishing", AC("perch"), 3, S, 6)
    profession_recipe("Fishing", AC("tambaqui"), 3, S, 6)
    profession_recipe("Fishing", AC("minnow"), 3, S, 8)
    profession_recipe("Fishing", AC("blackfish"), 3, S, 8)
    profession_recipe("Fishing", AC("pink_salmon"), 3, S, 10)
    profession_recipe("Fishing", AC("brown_trout"), 3, S, 10)
    profession_recipe("Fishing", AC("carp"), 3, S, 10)
    profession_recipe("Fishing", AC("pollock"), 3, S, 10)
    profession_recipe("Fishing", AC("smallmouth_bass"), 3, S, 10)
    profession_recipe("Fishing", AC("boulti"), 3, S, 10)
    profession_recipe("Fishing", AC("red_shrooma"), 3, S, 10)
    profession_recipe("Fishing", AC("brown_shrooma"), 3, S, 10)
    profession_recipe("Fishing", AC("gar"), 3, S, 13)
    profession_recipe("Fishing", AC("rainbow_trout"), 3, S, 13)
    profession_recipe("Fishing", AC("bayad"), 3, S, 13)
    profession_recipe("Fishing", AC("piranha"), 3, S, 13)
    profession_recipe("Fishing", AC("jellyfish"), 3, S, 13)
    profession_recipe("Fishing", AC("red_grouper"), 3, S, 13)
    profession_recipe("Fishing", AC("atlantic_cod"), 3, S, 13)
    profession_recipe("Fishing", AC("muskellunge"), 3, S, 15)
    profession_recipe("Fishing", AC("pacific_halibut"), 3, S, 15)
    profession_recipe("Fishing", AC("atlantic_halibut"), 3, S, 15)
    profession_recipe("Fishing", AC("catfish"), 3, S, 20)
    profession_recipe("Fishing", AC("capitaine"), 3, S, 20)
    profession_recipe("Fishing", AC("tuna"), 3, S, 20)
    profession_recipe("Fishing", AC("arapaima"), 3, S, 20)
    profession_recipe("Fishing", AC("arrau_turtle"), 3, S, 20)
    profession_recipe("Fishing", AC("box_turtle"), 3, S, 20)
    profession_recipe("Fishing", AC("starshell_turtle"), 3, S, 20)
    profession_recipe("Fishing", AC("goldfish"), 3, S, 20)
    profession_recipe("Fishing", AC("neptunium_ingot"), 5, S, 32)

    # Smithing
    profession_recipe("Smithing", MC("iron_boots"), 1, S, 2)
    profession_recipe("Smithing", MC("iron_leggings"), 1, S, 4)
    profession_recipe("Smithing", MC("iron_chestplate"), 1, S, 4)
    profession_recipe("Smithing", TC("blank_cast"), 1, S, 1)
    profession_recipe("Smithing", TC("ingot_cast"), 1, S, 2)
    profession_recipe("Smithing", TC("pickaxe_head_cast"), 1, S, 3)
    profession_recipe("Smithing", TC("gem_cast"), 1, S, 4)
    profession_recipe("Smithing", MC("iron_helmet"), 1, S, 3)
    profession_recipe("Smithing", MC("golden_boots"), 1, S, 4)
    profession_recipe("Smithing", MC("golden_leggings"), 1, S, 7)
    profession_recipe("Smithing", MC("golden_chestplate"), 1, S, 8)
    profession_recipe("Smithing", MC("golden_helmet"), 1, S, 5)
    profession_recipe("Smithing", MC("golden_apple"), 1, S, 10)
    profession_recipe("Smithing", MC("arrow"), 32, S, 3)
    profession_recipe("Smithing", MC("iron_sword"), 1, S, 1)
    profession_recipe("Smithing", TC("modifiable/two_handed"), 1, S, 1, True, "two_handed")
    profession_recipe("Smithing", MC("golden_sword"), 1, S, 2)


def make_professions():
    profession_card("Farming", 0xFFCC29, 0x81B214)
    profession_card("Carpentry", 0xD0AF84, 0x966C3B)
    profession_card("Mining", 0x1C1124, 0x88FFF7)
    profession_card("Masonry", 0x5E6F64, 0xBA7967)
    profession_card("Hunting", 0x393E46, 0xCF0000)
    profession_card("Cooking", 0xD8B384, 0xF7DAD9)
    profession_card("Smithing", 0xFFC93C, 0xFF7A00)


def make_trades():

    # Nature
    trade_card("Dirt", MC('dirt'), 16, 2, S, 0x513825, 0xA87954)
    trade_card("Sand", MC('sand'), 16, 4, S, 0xC2B289, 0xD8D6B9)
    trade_card("Gravel", MC('gravel'), 16, 2, S, 0x686160, 0xA19393)
    trade_card("Clay", MC('clay'), 16, 6, S, 0x878B95, 0x8E939D)
    trade_card("Ice", MC('ice'), 16, 16, S, 0x7E99CF, 0xABB8D0)
    trade_card("Blackstone", MC('blackstone'), 16, 12, S, 0x140E0F, 0x2D2831)
    trade_card("Grout", TC('grout'), 16, 12, S, 0x70737F, 0xAEB0B5)
    trade_card("Cobblestone", MC('cobblestone'), 16, 1, S, 0x585858, 0x646363)
    trade_card("Granite", MC('granite'), 16, 3, S, 0x563A2F, 0x9A6C5B)
    trade_card("Diorite", MC('diorite'), 16, 3, S, 0x7F7F7F, 0xD4D4D4)
    trade_card("Andesite", MC('andesite'), 16, 3, S, 0x5F5F5F, 0x8E8E8E)
    trade_card("Limestone", CR('limestone'), 16, 3, S, 0xA7A89E, 0xC0C2BA)
    trade_card("Weathered Limestone", CR('weathered_limestone'), 16, 3, S, 0x5E6055, 0x797E74)
    trade_card("Dolomite", CR('dolomite'), 16, 3, S, 0xC2C2C2, 0xDADADA)
    trade_card("Gabbro", CR('gabbro'), 16, 3, S, 0x6B5D4F, 0x7D6B5A)
    trade_card("Scoria", CR('scoria'), 16, 3, S, 0x2A130C, 0x553427)
    trade_card("Dark Scoria", CR('dark_scoria'), 16, 3, S, 0x0D0706, 0x23201A)
    trade_card("Obsidian", MC('obsidian'), 1, 8, S, 0x05030A, 0x36234C)

    # Carpentry
    trade_card("Dead Log", BOP('dead_log'), 16, 2, S, 0x3D362D, 0x7A756D)
    trade_card("Oak Log", MC('oak_log'), 16, 4, S, 0x735932, 0xA88756)
    trade_card("Birch Log", MC('birch_log'), 16, 4, S, 0xD6D6D2, 0xC4B079)
    trade_card("Spruce Log", MC('spruce_log'), 16, 4, S, 0x523E21, 0x6F522F)
    trade_card("Jungle Log", MC('jungle_log'), 16, 4, S, 0x5A501D, 0x9B6E4C)
    trade_card("Acacia Log", MC('acacia_log'), 16, 4, S, 0x4F4B42, 0x9E552E)
    trade_card("Dark Oak Log", MC('dark_oak_log'), 16, 4, S, 0x2C1B0D, 0x422B15)
    trade_card("Crimson Stem", MC('crimson_stem'), 16, 8, S, 0x442332, 0x7A3852)
    trade_card("Warped Stem", MC('warped_stem'), 16, 8, S, 0x3E1E2D, 0x347776)

    # Mining
    trade_card("Iron Ingot", MC('iron_ingot'), 8, 16, S, 0xA6A6A6, 0xD5D5D5)
    trade_card("Zinc Ingot", CR('zinc_ingot'), 8, 16, S, 0x616A60, 0xD0D2C5)
    trade_card("Copper Ingot", CR('copper_ingot'), 8, 16, S, 0xDD7E5D, 0xFCEFBA)
    trade_card("Nickel Ingot", TE('nickel_ingot'), 8, 32, S, 0x977756, 0xE4D196)
    trade_card("Lead Ingot", TE('lead_ingot'), 8, 32, S, 0x232456, 0x7C95A4)
    trade_card("Gold Ingot", MC('gold_ingot'), 8, 48, S, 0xD99413, 0xFAF25E)
    trade_card("Andesite Alloy", CR('andesite_alloy'), 16, 8, S, 0x505050, 0x878787)
    trade_card("Brass Ingot", CR('brass_ingot'), 8, 48, S, 0x6F3C2D, 0xFCF085)
    trade_card("Invar Ingot", TE('invar_ingot'), 4, 64, S, 0x406D6C, 0xC3CAC1)
    trade_card("Coal", MC('coal'), 16, 4, S, 0x1C1C1E, 0x383D45)
    trade_card("Flint", MC('flint'), 16, 4, S, 0x3C3B3B, 0xA6A6A6)
    trade_card("Cinnabar", TE('cinnabar'), 4, 16, S, 0xFC7781, 0xFCCED0)
    trade_card("Redstone Dust", MC('redstone'), 16, 8, S, 0xA80F01, 0xFC7781)
    trade_card("Diamond", MC('diamond'), 1, 1, G, 0x20C3B3, 0xD2FCF3)
    trade_card("Lapis Lazuli", MC('lapis_lazuli'), 8, 32, S, 0x335DC1, 0x7395E7)
    trade_card("Emerald", MC('emerald'), 1, 1, G, 0x00A82B, 0xADFACB)
    trade_card("Sulfur", TE('sulfur'), 4, 8, S, 0xC7A94A, 0xEEF071)
    trade_card("Apatite", TE('apatite'), 4, 8, S, 0x27A9BB, 0x2CC7C9)
    trade_card("Niter", TE('niter'), 4, 8, S, 0x735A65, 0xB8AFAF)
    trade_card("Nether Quartz", MC('quartz'), 8, 24, S, 0xB19E8F, 0xE7E2DB)
    trade_card("Certus Quartz", AE2('certus_quartz_crystal'), 8, 24, S, 0x91C5FC, 0xA7CBCF)
    trade_card("Fluix Quartz", AE2('fluix_crystal'), 8, 32, S, 0x8F5CCB, 0xFC7ED4)
    trade_card("Cured Rubber", TE('cured_rubber'), 6, 16, S, 0x3D363C, 0x594F55)

    # Misc
    trade_card("Scaffolding", MC('scaffolding'), 16, 2, S, 0x7F5F41, 0xDDC683)
    trade_card("Wool", MC('white_wool'), 1, 8, S, 0xBEC4C5, 0xE4E4E4)
    trade_card("Sponge", MC('sponge'), 1, 16, S, 0x8F8234, 0xCDCF4A)
    trade_card("Cobweb", MC('cobweb'), 1, 16, S, 0xC2CCCF, 0xFCFCFC)

    # Farming
    trade_card("Rice", FD('rice_bag'), 1, 4, S, 0x9F7653, 0xCEC6BC)
    trade_card("Straw", FD('straw'), 32, 8, S, 0x623A17, 0x966537)
    trade_card("Glowshroom", BOP('glowshroom'), 4, 9, S, 0x2C65C9, 0x83A7B7)
    trade_card("Bramble", BOP('bramble'), 4, 9, S, 0x8C3122, 0xECCDBC)
    trade_card("Barley", BOP('barley'), 4, 4, S, 0xB78B44, 0xD8BC64)
    trade_card("Watergrass", BOP('watergrass'), 4, 4, S, 0x43763D, 0x538B51)
    trade_card("Mangrove Root", BOP('mangrove_root'), 4, 9, S, 0x795740, 0xB8AB88)
    trade_card("Reed", BOP('reed'), 4, 5, S, 0x7B4E35, 0xB2855C)
    trade_card("Clover Petal", BOP('huge_clover_petal'), 4, 10, S, 0x5B8A4F, 0x6FA960)
    trade_card("Spanish Moss", BOP('spanish_moss'), 4, 7, S, 0x395B2A, 0xA2C790)
    trade_card("Willow Vine", BOP('willow_vine'), 4, 7, S, 0x265F0D, 0x317B10)
    trade_card("Cattail", BOP('cattail'), 4, 4, S, 0x186B2B, 0x845738)
    trade_card("Sugar Cane", MC('sugar_cane'), 4, 3, S, 0x688546, 0xC5FC85)
    trade_card("Kelp", MC('kelp'), 8, 3, S, 0x5B8131, 0x58A92F)
    trade_card("Bamboo", MC('bamboo'), 8, 5, S, 0x4F7416, 0x88AC5F)
    trade_card("Sweet Berries", MC('sweet_berries'), 8, 11, S, 0x27613F, 0xA30700)
    trade_card("Vines", MC('vine'), 4, 7, S, 0x183D08, 0x317B10)
    trade_card("Tree Fertilizer", CR('tree_fertilizer'), 1, 8, S, 0xCF8469, 0x71933A)

    # Masonry
    trade_card("Daub", SP('daub'), 16, 5, S, 0xBFBAAA, 0xCBC8B6)
    trade_card("Clear Glass", TC('clear_glass'), 16, 4, S, 0xA9C3CF, 0xE8E8E8)
    trade_card("Copper Shingles", CR('copper_shingles'), 16, 3, S, 0xB5654B, 0xE4BB79)
    trade_card("Algal Bricks", AP('algal_bricks'), 32, 6, S, 0x292926, 0x3D4D48)
    trade_card("Olivestone Bricks", AP('olivestone_bricks'), 32, 8, S, 0x3A3C2E, 0x57553E)
    trade_card("Architect's Limestone", AP('limestone'), 32, 8, S, 0x756958, 0x7F7360)
    trade_card("Sunmetal", AP('sunmetal_block'), 32, 8, S, 0x603E38, 0xB48764)
    trade_card("Plating Block", AP('plating_block'), 32, 8, S, 0x222225, 0x39383C)
    trade_card("Twisted Planks", AP('twisted_planks'), 32, 8, S, 0x5E5259, 0x72616B)
    trade_card("Osseous Bricks", AP('osseous_bricks'), 32, 8, S, 0x9D976F, 0xD3D0BF)
    trade_card("Seared Stone", TC('seared_stone'), 16, 32, S, 0x393734, 0x59534F)
    trade_card("Scorched Stone", TC('scorched_stone'), 16, 32, S, 0x382C25, 0x4C3F37)
    trade_card("Lantern", MC('lantern'), 1, 1, S, 0x484F64, 0xF6C765)
    trade_card("Copper Lantern", SP('copper_lantern'), 1, 1, S, 0xB36535, 0xF3B154)
    trade_card("Brass Lantern", SP('brass_lantern'), 1, 1, S, 0xA47C37, 0xFAEACF)
    trade_card("Crimson Lantern", SP('crimson_lantern'), 1, 1, S, 0x9C0E2C, 0xE7EB56)

    # Hunting
    trade_card("Slime Ball", MC('slime_ball'), 4, 24, S, 0x4F7E48, 0x8AD480)
    trade_card("String", MC('string'), 4, 5, S, 0x2E4446, 0xD8D8D8)
    trade_card("Feather", MC('feather'), 4, 6, S, 0xD0D0D0, 0xFCFCFC)
    trade_card("Gunpowder", MC('gunpowder'), 4, 7, S, 0x535353, 0x717171)
    trade_card("Leather", MC('leather'), 4, 8, S, 0x873A25, 0xC45B34)
    trade_card("Ink Sac", MC('ink_sac'), 4, 8, S, 0x493F49, 0x786470)
    trade_card("Experience", MC('experience_bottle'), 1, 8, S, 0x689AC7, 0xFFF2FF)
    trade_card("Shulker Shell", MC('shulker_shell'), 1, 2, G, 0x6B476A, 0x956895)
    trade_card("Spider Eye", MC('spider_eye'), 4, 10, S, 0x64062A, 0xC25E6A)
    trade_card("Ender Pearl", MC('ender_pearl'), 1, 48, S, 0x0B4C41, 0x2BCBAF)
    trade_card("Rotten Flesh", MC('rotten_flesh'), 4, 3, S, 0xB24320, 0x695C18)
    trade_card("Blaze Rod", MC('blaze_rod'), 1, 20, S, 0xAC3B00, 0xD5AC26)
    trade_card("Bone", MC('bone'), 4, 8, S, 0xC9C4A3, 0xC9C4A3)
    trade_card("Prismarine Shard", MC('prismarine_shard'), 4, 16, S, 0x2F6355, 0x8FC0AA)
    trade_card("Prismarine Crystals", MC('prismarine_crystals'), 4, 24, S, 0x71A296, 0xDCE6D9)
    trade_card("Witch Hat", RQ('witch_hat'), 1, 1, G, 0x424242, 0x568125)
    trade_card("Zombie heart", RQ('zombie_heart'), 1, 32, S, 0x532B38, 0x8D584A)
    trade_card("Squid Beak", RQ('squid_beak'), 1, 32, S, 0x00613B, 0x5BCDA1)
    trade_card("Rib Bone", RQ('rib_bone'), 1, 32, S, 0xDFDDCE, 0xFAF9E9)
    trade_card("Catalyzing Gland", RQ('catalyzing_gland'), 1, 48, S, 0x268E23, 0x63CA52)
    trade_card("Chelicerae", RQ('chelicerae'), 1, 32, S, 0x251721, 0x4D0C3B)
    trade_card("Slime Pearl", RQ('slime_pearl'), 1, 48, S, 0x1B9D33, 0x84F58E)
    trade_card("Bat Wing", RQ('bat_wing'), 1, 2, G, 0x464646, 0x6D6D6D)
    trade_card("Withered Rib", RQ('withered_rib'), 1, 2, G, 0x2A2E2E, 0x434949)
    trade_card("Molten Core", RQ('molten_core'), 1, 48, S, 0xED7102, 0xFAFC58)
    trade_card("Eye of the Storm", RQ('eye_of_the_storm'), 1, 2, G, 0xFCD607, 0x96FC52)
    trade_card("Frozen Core", RQ('frozen_core'), 1, 48, S, 0x008DC2, 0x7571FB)
    trade_card("Nebulous Heart", RQ('nebulous_heart'), 1, 1, G, 0x6200A0, 0xE500C3)
    trade_card("Guardian Spike", RQ('guardian_spike'), 1, 1, G, 0x7F4215, 0xE29964)
    trade_card("Phantom Membrane", MC('phantom_membrane'), 1, 48, S, 0x6E506B, 0xC1B79F)
    trade_card("Blaze Cake", CR('blaze_cake'), 1, 16, S, 0x834141, 0xFCE083)


def make_exchanges():
    exchange_card("Exchange Currencies", S, G, 0xEBA83A, 0xF4F4F4)
    # exchange_card("Exchange Private Currencies", B, I, 0x7A4318, 0x406D6C)


if __name__ == '__main__':
    make_products()
    make_professions()
    make_trades()
    make_exchanges()
